### ISSUE TITLE
TODO blocks in developer documentation

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#71]
The following pages have missing information (search for "TODO" on the page):
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_setup
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_versions
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_testing_code#manually-on-your-local-computer
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_contribution#github-issues Also need to update images on this page so they follow the same colour schemes as elsewhere.
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_review
- [ ] https://staging.libcellml.org/documentation/developers/v0.2.0/dev_coding_standards#variable-naming Needs clarification here?
- [ ]
